# Generated by Django 4.0.2 on 2022-02-13 01:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_contactcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablecontacttime',
            name='day_of_week',
            field=models.CharField(choices=[('M', 'Monday'), ('Tu', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], default='M', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availablecontacttime',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 2, 13, 1, 29, 3, 146181, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availablecontacttime',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2022, 2, 13, 1, 29, 9, 196433, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
