# Generated by Django 4.0.2 on 2022-02-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_resettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='value',
            field=models.BigIntegerField(),
        ),
    ]
